"""
auth/pages/forgot_password.py
------------------------------
Forgot password flow: Email → OTP → New password.

Steps managed via st.session_state.forgot_step:
  "email"    — user enters email, requests OTP
  "otp"      — user enters 6-digit OTP received by email
  "reset"    — user enters and confirms new password

Security
--------
- OTP is generated by auth/otp.py (cryptographically secure).
- OTP is stored in SQLite via auth/db.store_otp (5-minute expiry).
- OTP is sent via SMTP using auth/email_sender.send_otp_email.
- OTP value is NEVER displayed in the UI — it is only emailed.
- OTP is cleared from the database immediately after successful verification.
"""

from __future__ import annotations

import streamlit as st

from auth.db import email_exists, store_otp, verify_otp, reset_password, init_db
from auth.otp import generate_otp, is_valid_otp_format
from auth.email_sender import send_otp_email, is_smtp_configured, SendResult

_MIN_PASSWORD_LENGTH = 8


def render() -> None:
    init_db()

    # Initialise step state
    if "forgot_step" not in st.session_state:
        st.session_state.forgot_step = "email"
    if "forgot_email" not in st.session_state:
        st.session_state.forgot_email = ""

    _, col, _ = st.columns([1, 1.6, 1])
    with col:
        st.markdown("""
        <div class="ep-auth-logo">
            <div class="ep-auth-icon">⚡</div>
            <div class="ep-auth-brand">EcoPulse AI</div>
            <div class="ep-auth-tagline">Intelligent Energy. Sustainable Future.</div>
        </div>
        """, unsafe_allow_html=True)

        step = st.session_state.forgot_step

        if step == "email":
            _step_email(col)
        elif step == "otp":
            _step_otp(col)
        elif step == "reset":
            _step_reset(col)


# ---------------------------------------------------------------------------
# Step 1 — Email input
# ---------------------------------------------------------------------------

def _step_email(_col) -> None:
    st.markdown('<div class="ep-auth-title">Forgot Password</div>', unsafe_allow_html=True)
    st.markdown(
        '<p class="ep-auth-subtitle">Enter your registered email address and we\'ll send a 6-digit OTP.</p>',
        unsafe_allow_html=True,
    )

    with st.form("forgot_email_form"):
        email = st.text_input("Email address", placeholder="you@example.com", key="fp_email")
        submitted = st.form_submit_button("Send OTP", use_container_width=True, type="primary")

    if submitted:
        if not email or not email.strip():
            st.error("Please enter your email address.")
        elif not email_exists(email):
            # Security: don't reveal whether the email exists
            st.info(
                "If that email is registered, you will receive an OTP shortly. "
                "Please check your inbox (and spam folder)."
            )
        elif not is_smtp_configured():
            st.error(
                "Email sending is not configured. "
                "Please add SMTP_HOST, SMTP_PORT, SMTP_USER, and SMTP_PASSWORD to your .env file."
            )
        else:
            otp_code, expires_at = generate_otp()
            stored = store_otp(email.strip().lower(), otp_code, expires_at)
            if stored:
                result = send_otp_email(email.strip().lower(), otp_code)
                if result == SendResult.OK:
                    st.session_state.forgot_email = email.strip().lower()
                    st.session_state.forgot_step = "otp"
                    st.success("OTP sent! Check your inbox.")
                    st.rerun()
                elif result == SendResult.AUTH_FAILURE:
                    st.error(
                        "Gmail rejected the App Password. "
                        "Please generate a new App Password at "
                        "Google Account → Security → App Passwords, "
                        "update SMTP_PASSWORD in .env, and restart the app."
                    )
                elif result == SendResult.NETWORK_FAILURE:
                    st.error(
                        "Could not connect to smtp.gmail.com. "
                        "Please check your network connection and try again."
                    )
                else:
                    st.error(
                        "Failed to send the OTP email. "
                        "Please verify your SMTP settings in .env and try again."
                    )
            else:
                st.error("Could not find that account. Please check the email address.")

    st.markdown('<hr style="border-color:var(--ep-border);margin:16px 0 12px;">', unsafe_allow_html=True)
    if st.button("← Back to Sign In", use_container_width=True, key="fp_back_email"):
        st.session_state.auth_page = "login"
        st.session_state.forgot_step = "email"
        st.rerun()


# ---------------------------------------------------------------------------
# Step 2 — OTP verification
# ---------------------------------------------------------------------------

def _step_otp(_col) -> None:
    email = st.session_state.forgot_email

    st.markdown('<div class="ep-auth-title">Enter OTP</div>', unsafe_allow_html=True)
    st.markdown(
        f'<p class="ep-auth-subtitle">Enter the 6-digit OTP sent to <strong>{email}</strong>. '
        f'It expires in 5 minutes.</p>',
        unsafe_allow_html=True,
    )

    with st.form("otp_form"):
        otp = st.text_input(
            "6-digit OTP",
            placeholder="000000",
            max_chars=6,
            key="fp_otp",
        )
        submitted = st.form_submit_button("Verify OTP", use_container_width=True, type="primary")

    if submitted:
        if not is_valid_otp_format(otp):
            st.error("Please enter a valid 6-digit OTP.")
        else:
            valid = verify_otp(email, otp)
            if valid:
                st.session_state.forgot_step = "reset"
                st.rerun()
            else:
                st.error("Invalid or expired OTP. Please request a new one.")

    st.markdown('<hr style="border-color:var(--ep-border);margin:16px 0 12px;">', unsafe_allow_html=True)
    col_resend, col_back = st.columns(2)
    with col_resend:
        if st.button("Resend OTP", use_container_width=True, key="fp_resend"):
            if is_smtp_configured() and email_exists(email):
                otp_code, expires_at = generate_otp()
                store_otp(email, otp_code, expires_at)
                result = send_otp_email(email, otp_code)
                if result == SendResult.OK:
                    st.success("New OTP sent to your email.")
                elif result == SendResult.AUTH_FAILURE:
                    st.error(
                        "Gmail rejected the App Password. "
                        "Please regenerate it at Google Account → Security → App Passwords."
                    )
                else:
                    st.error("Failed to resend OTP. Please check SMTP settings in .env.")
            else:
                st.error("Cannot resend — SMTP not configured or email not found.")
    with col_back:
        if st.button("← Back", use_container_width=True, key="fp_back_otp"):
            st.session_state.forgot_step = "email"
            st.rerun()


# ---------------------------------------------------------------------------
# Step 3 — New password
# ---------------------------------------------------------------------------

def _step_reset(_col) -> None:
    email = st.session_state.forgot_email

    st.markdown('<div class="ep-auth-title">Set New Password</div>', unsafe_allow_html=True)
    st.markdown(
        '<p class="ep-auth-subtitle">OTP verified. Choose a strong new password.</p>',
        unsafe_allow_html=True,
    )

    with st.form("reset_form"):
        new_pass = st.text_input(
            "New Password",
            type="password",
            placeholder=f"Min {_MIN_PASSWORD_LENGTH} characters",
            key="fp_new_pass",
        )
        confirm = st.text_input(
            "Confirm New Password",
            type="password",
            placeholder="Repeat new password",
            key="fp_confirm_pass",
        )
        submitted = st.form_submit_button(
            "Reset Password", use_container_width=True, type="primary"
        )

    if submitted:
        if len(new_pass) < _MIN_PASSWORD_LENGTH:
            st.error(f"Password must be at least {_MIN_PASSWORD_LENGTH} characters.")
        elif new_pass != confirm:
            st.error("Passwords do not match.")
        else:
            ok = reset_password(email, new_pass)
            if ok:
                # Clean up forgot-flow state
                st.session_state.forgot_step = "email"
                st.session_state.forgot_email = ""
                st.session_state.auth_page = "login"
                st.success("Password reset successfully! You can now sign in.")
                st.rerun()
            else:
                st.error("Could not reset password. Please try again.")
